### ISSUE TITLE
[29-10-2022]: API DOCUMENTATION

### ISSUE THREAD

**Issue by anslemkelechi** [Open-Science-Community-Saudi-Arabia/MOOCs#105]
#### Description

- [x] *API Documentation for API endpoints.*

#### Which task are you working on?

- [x] *Use Postman to test endpoints*
- [x] *Write documentation in postman*

### Who want to work on this issue?

I would be working on this issue. 

Parent Issue : #5

**Comment by RealRichi3** [comment]
@anslemkelechi i have added the initial API doc i made, it only covers the Authentication routes, you can check `/backend_API/src/API doc`

**Comment by RealRichi3** [comment]
@anslemkelechi what's the update on this
