### ISSUE TITLE
[05/11/2022] Backend API test deployment

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/MOOCs#113]
#### Description
Deploy API to any cloud platform for test for test 

I'll go for Google cloud platform.

### What needs to be done?
- [x] *Deploy API to google cloud platform*
- https://moocs-test.onrender.com 
- [x] *Update API host link*

**Comment by RealRichi3** [comment]
I tried using GCP but i had issues setting up a free tier account so i switched to Render

**Comment by BatoolMM** [comment]
Thank you @RealRichi3 but the link doesn’t work!

**Comment by RealRichi3** [comment]
@BatoolMM should i also host the front end app?

**Comment by sandygudie** [comment]
@RealRichi3 the API is not connected to the frontend yet, so it can not be tested from there. I suggest you share the PostMan UI doc for the APIs where sample data can be used for testing. you could also use Swagger UI, but Postman UI is also great.

**Comment by RealRichi3** [comment]
@sandygudie I already added the API documentation for the authentication routes you can check [here](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/blob/9f3a5b959ecfb9ab8aeddaa8cff2e74e9e61c32c/backend_API/src/API%20doc/MOOCs.postman_collection.json)

It's in JSON format, so you can import it to postman

**Comment by BatoolMM** [comment]
@sandygudie @RealRichi3 I think you should host the front-end app, feel free to merge the PRs related to the front end after getting reviewed. https://moocs-test.onrender.com doesn't work. Let me know if you need any help in merging the PRs in the `dev_team2` branch.

**Comment by RealRichi3** [comment]
Alright @BatoolMM

**Comment by sandygudie** [comment]
Yes @RealRichi3 i will host the frontend
