### ISSUE TITLE
[13/10/2022]: Setup Frontend for MOOC Platform

### ISSUE THREAD

**Issue by Meekunn** [Open-Science-Community-Saudi-Arabia/MOOCs#12]
#### Description
I would like to set up the Frontend for the OSCSA MOOC PLATFORM.
The parent Issue is #10 

#### Which task are you working on?

- [ ] *Create React App in `dev` branch*
- [ ] *Task 1- Set Up Prettier/Eslint*

#### Who wants to work on this issue?
I would like to work on this issue @BatoolMM and follow updates on the parent issue

**Comment by mufidat3250** [comment]
@Meekunn are you done creating it

**Comment by Meekunn** [comment]
Yes, I'm about to create a PR @mufidat3250

**Comment by BatoolMM** [comment]
Thank you, all for your hard work. I will close this issue now!
