### ISSUE TITLE
[12/10/2022]: Backend API [task] - Setup Project structure

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/MOOCs#13]
Sub issue for tasks in #5 

### Summary
Add project structure for BACKEND API for MOOCs platform

Should be like this
```
.....
backend_API/
  -- node_modules/
  -- src/
       -- controllers/
       -- routes/
           -- routes_handler.js
       -- models/
       -- db/
       -- test/
       -- utils/
             -- async_wrapper.js
             -- config.js
       -- .env
       -- app.js
       -- server.js
package-lock.json
package.json
```
### What needs to be done?
- Setup express server
- Setup database connection
- MVC app structure

- [x] *Setup express server*
- [x] *Setup database connection.*
- [x] *Setup MVC app structure*

### Who want to work on this issue?
I would work on this issue

**Comment by anslemkelechi** [comment]
Awesome work @RealRichi3

**Comment by ORIYOMI289** [comment]
@RealRichi3 we will be waiting for you on this, before cloning the repo. hope it wont take long

**Comment by ORIYOMI289** [comment]
it seems like the structure is created, on what branch is it ?

**Comment by RealRichi3** [comment]
Sure, i think @BatoolMM would have a zoom session with us today, we need more clarification on how the branch for develop will be managed, regarding reviewing pull requests and some other issues. Once it's ready I'll let everyone know

**Comment by BatoolMM** [comment]
@RealRichi3 https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/14#issuecomment-1278773676

Let me and @alswajiab know if you need any support or help 🍀

**Comment by RealRichi3** [comment]
Alright thanks
