### ISSUE TITLE
[13-10-2022]: Folder structure and route of the front end project

### ISSUE THREAD

**Issue by mufidat3250** [Open-Science-Community-Saudi-Arabia/MOOCs#16]
#### Description

I would like to  work on the folder structure  and route of the front end project 
The parent Issue is https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/10

#### Which task are you working on?

- [ ] *Header*
- [ ] *Footer*
- [ ] *Login page*
- [ ] *Sign Up page*
- [ ] *Reset Password*
- [ ] *Profile page*
- [ ] *History page*
- [ ] *Course Detail Page*
- [ ] *Settings page*
- [ ] *admin page*
### What needs to be done?

- [ ] *create the folder structure*
- [ ] *Route all the pages using react Router dom*

### Who want to work on this issue?

I would like to work on this issue @BatoolMM and follow updates on the parent issue

**Comment by BatoolMM** [comment]
Thank you @mufidat3250, let me know if you need anything from me!

**Comment by Meekunn** [comment]
@mufidat3250 I would like to collaborate with you on this issue. Which task are you currently working on and which can I work on?

**Comment by sandygudie** [comment]
@mufidat3250 please can you pick a task to work on for this issue, not everything

**Comment by Eshy10** [comment]
@mufidat3250 I would like to collaborate with you on this issue.

**Comment by mufidat3250** [comment]
i am not working on all the task i am only creating a folder structure and the route so as to simplify things  for all of us that will be collaborating. in order to avoid mix up . so that all you need to do is to start working on task by following the existing format. @sandygudie. @Eshy10 @Meekunn

**Comment by mufidat3250** [comment]
Alright @BatoolMM

**Comment by mufidat3250** [comment]
@BatoolMM @Meekunn  I am done with the task  task but i am confuse of the branch i am to make a pull request against is it the dev branch or the main branch

**Comment by sandygudie** [comment]
We are using the `dev_team2` branch

**Comment by mildrette** [comment]
hey everyone please so far which are the task taking here ???
