### ISSUE TITLE
[14-10-2022]: Develop Header and Footer for MOOC App

### ISSUE THREAD

**Issue by Meekunn** [Open-Science-Community-Saudi-Arabia/MOOCs#19]
#### Description
Develop the Header and Footer section of the MOOC App referencing the Design template from issue #11. 

#### Which task are you working on?

- [ ] *Develop Header.*
- [ ] *Develop Footer.*

### What needs to be done?

- [ ] *Develop Header and Footer Section*

### Who want to work on this issue?

Kindly assign to me, @BatoolMM. I want to work on this issue and follow up on updates from Parent issue #10.

**Comment by mufidat3250** [comment]
i would like to collaborate with you on this issue how   do we get started

**Comment by Meekunn** [comment]
@mufidat3250, I will suggest we wait for the PR on the Frontend Project Structure for the new branch to be merged. Let me know if you think we can go ahead without that.

**Comment by mufidat3250** [comment]
sure we can since it is already @BatoolMM  has already assigned the issue.  what have you worked on and how can i come in

**Comment by mufidat3250** [comment]
@Meekunn  it seams the pull request has being merged

**Comment by Meekunn** [comment]
@mufidat3250 Yes, it has been merged. YOu can take up the footer while I work on the header. Don't forget to consider responsiveness.

**Comment by mufidat3250** [comment]
Alright i will look into it

**Comment by mufidat3250** [comment]
@Meekunn pls i want to ask that how do you add image to your PR i mean the a screenshot of the work done.

**Comment by Meekunn** [comment]
@mufidat3250 I use the drag and drop option. You can also copy the image and paste it in the comment box.

**Comment by mufidat3250** [comment]
@Meekunn i will try it out thanks

**Comment by mufidat3250** [comment]
@Meekunn how about the number of task  i noticed  some  issue has 3 task while some have 1 task, how do they keep track of it when making a pull request.
