### ISSUE TITLE
 OSCSA MOOCs Platform

### ISSUE THREAD

**Issue by sandygudie** [Open-Science-Community-Saudi-Arabia/MOOCs#2]
**Problem Statement**
Open Science Community would like to develop Massive Open Online Courses (MOOCs), which are free online courses available for anyone to enroll in. We have developed our own materials and will also reuse materials from Open Life Sciences and Turing Way. In order to do that, we need to develop a platform where a participant can log in, and view videos and written materials as lessons. This will be similar to [Udemy](https://www.udemy.com/) and other platforms for MOOCs. 
Your task is to create a demo of the website using any backend technology. You don't have to create the next Udemy, only a demo and showing how you can implement functionality in the website.

**Functionalities**
- Users  can log in and log out
- Users can access OSCSA videos
- Users can access lesson materials
- Arabic translations available
- **(please suggest other suitable features)**

**Discussions/Planning**
- The issue is open to suggestions on tools and technology suitable for this platform.
- Open to collaboration in **Frontend Development, Design, and Backend Development.**
- PLS ADD YOUR THOUGHTS: https://docs.google.com/document/d/1S31oJKEVf-ywlTEDUf4dHDiUVmCbYWVYE1QbPScLFis/edit

DEVELOPMENT PROCESS:
- DESIGN issue #11
- FRONTEND DEVELOPMENT issue #10 
- BACKEND DEVELOPMENT issue #5 

#### DEVELOPMENT PROGRESS
**Design** 
- [x] Landing page, Sign up, and login pages  
Issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/11 
Figma [link](https://www.figma.com/file/mkhBuJAS2arzy3wrbTZp2D/Simple-Landing-page-for-OSCSA%2C-with-Log-In-and-Sign-Up-Pages?node-id=0%3A1) 

**Frontend Development**
- [x] Set up Project structure
 issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/20
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/21
- [x] Landing-page 
issue : https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/36
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/43
- [x] Header 
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/19
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/37
- [x] Footer
 issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/19
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/37
- [x] Login 
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/24
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/31
- [x] Sign up page 
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/24
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/31

**Backend Development**
* [x]  Setup project structure
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/13
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/14
* [x]  Database model for users and admin and passwords
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/30
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/32
 * [x]  Asynchronous function wrappers -(abstracts try catch block)
 issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/33
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/34
* [x]  Error handler middleware
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/33
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/34
* [x] Authentication middleware
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/44
 * [x] Permissions router middleware
 issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/45
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/46
 * [x]  Signup
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/7
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/38
 * [x]  Login
issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/7
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/38
 * [x]  Social signin/signup with Google 
 issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/48
PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/49

**Comment by sandygudie** [comment]
**Suggestions**
Frontend Development: ReactJS
Backend: 
  - Firebase for login authentication(Google)  or
  -  MongoDB for Database(UserAPI, etc) ;
  -  We could use Cloudinary to store videos and lesson materials

**Comment by ladyami** [comment]
but i am already on this task i have created issue

**Comment by BatoolMM** [comment]
@sandygudie and @sandygudie, both of you can create a proposal - we allow multiple submissions for this task.

**Comment by safa-ismail** [comment]
> 

Hi .. i have no knowledge of react js. Can I work on the html and css part ??

**Comment by Dhei-vid** [comment]
I have experience working with React JS.

**Comment by Teslimsama** [comment]
I only have experience in html,css,PHP,js

**Comment by ORIYOMI289** [comment]
@sandygudie can we have access to the mongodb database and cloudinary, to be used for the project ?

**Comment by AminMusah** [comment]
hi @sandygudie I have experience with React and firebase. i am interested in contributing to this project.

**Comment by sandygudie** [comment]
Hello Team, thank you for the interest to collaborate in this tasks.

Tha project will be broken down into smaller tasks so that everyone can contribute.
Since it’s a demo project we will use a private account for tools needed (cloudinary, MongoDB etc)
Design- We will need a design template for this project.
Aside what I suggested ,feel free to highlight alternative approach to it.

Regrading collaboration, I will suggest a Slack workspaces, @BatoolMM  this will also be helpful for long term collaboration/discussion in OSCSA , otherwise we continue here. 

Thank you

**Comment by safa-ismail** [comment]
Hi team, i would like to take the initiative for designing and @BatoolMM  May i know how many pages does the demo need? Login page, landing page. Do we need more ?

**Comment by sandygudie** [comment]
> Hi team, i would like to take the initiative for designing and @BatoolMM May i know how many pages does the demo need? Login page, landing page. Do we need more ?

Thank you 
Login page and Dashboard pages 
We may not need a landing page for now

**Comment by okerekechinweotito** [comment]
@sandygudie  Have you created the slack channel ?.  Lets fix a meeting later today so we can decide on the features the site will carry. And then break down the task into multiple issues.

**Comment by Dhei-vid** [comment]
I agree with @okerekechinweotito, we should create either slack or discord channel so everyone is up to speed.

**Comment by ladyami** [comment]
@Dhei-vid slack is okay the project should be break down

**Comment by Dhei-vid** [comment]
I will go ahead and create a slack channel, then post the link here.

**Comment by sandygudie** [comment]
Hello Team, I totally agree with the slack workspace, I am hoping we could have an official OSCSA Slack Workspace rather than a private workspace,  @BatoolMM hoping to hear your suggest on this .

**Comment by sandygudie** [comment]
> I will go ahead and create a slack channel, then post the link here.

@Dhei-vid I already created one but let's hear from @BatoolMM

**Comment by Dhei-vid** [comment]
Heres the link for the slack channel -  https://join.slack.com/t/slack-qni4624/shared_invite/zt-1hmp78eae-jkh8wKPB3M_A52IyBqWhDA

**Comment by okerekechinweotito** [comment]
@BatoolMM  pls what do you think about the suggestions above

**Comment by Kemmie001** [comment]
@sandygudie I can work with ReactJs we can split different pages and features into issues so everyone can contribute and be up to speed

**Comment by Kemmie001** [comment]
This is a list of all the pages we will need then we can start breaking them into chunks and creating issues out of them and their features.

- Landing Page
- Login
- Signup
- User dashboard
- Course page
- Admin dashboard
- Upload Course Page
- Edit Course Page
- View Course Page 

We can add more. We will need people to handle UI/UX, Frontend, Backend, and project management for all of these.

**Comment by oEbuka** [comment]
Users should also be able to register in order to Log in. I would suggest we add this. 
I would be working on this task, implementing REACT, Mongo DB , Node JS

**Comment by okerekechinweotito** [comment]
@Kemmie001  Lets wait to receive some clarifications from the Mentor then we can arrange a meeting and properly plan and outline this

**Comment by sandygudie** [comment]
Hello Team, While waiting on feedback from @BatoolMM 
Please, Let's have a call by 5 PM WAT today( 9 AM PST)

**Comment by RealRichi3** [comment]
@sandygudie I suggest there should be different types of users

One would be an admin for uploading the OSCA videos
Then the normal user for just accessing the videos
The admin can also have other functionalities too

**Comment by victorvictoria-maker** [comment]
> Hello Team, While waiting on feedback from @BatoolMM Please, Let's have a call by 5 PM WAT today( 9 AM PST) https://meet.google.com/zth-eoem-nnx

I would join the meeting as I would like to contribute to it too

**Comment by safa-ismail** [comment]
> Hello Team, While waiting on feedback from @BatoolMM Please, Let's have a call by 5 PM WAT today( 9 AM PST) https://meet.google.com/zth-eoem-nnx

Will be joining the meeting too..

**Comment by Dhei-vid** [comment]
> Users should also be able to register { creating a register page }in order to Log in. I would suggest we add this. I would be working on this task, implementing REACT, Mongo DB , Node JS

so we agree we will be making use of MongoDB. I would like to work on the login and register pages so we could team up to do that.

**Comment by ORIYOMI289** [comment]
lets all wait for the meeting by 5pm then

**Comment by BatoolMM** [comment]
Thank you, @sandygudie, for creating a clear issue using the issue template - and thanks for everyone who joined this issue @Dhei-vid @Kemmie001 @AminMusah @ORIYOMI289 @okerekechinweotito @victorvictoria-maker @RealRichi3 @oEbuka @ladyami @safa-ismail @Teslimsama @codeinvoke7.
> Apologies if I missed any names! 

This is supposed to be a demo with a minimum landing page with the courses, sign-up/log-in page, and a Course page that has videos and coding exercises. You don't necessarily need to add them all, but the PR should be on this repository!

In terms of using slack, we recommend that any collaboration uses GitHub issues and GitHub Discussion but you are very welcome to use any other platforms. We can't monitor both Slack and GitHub at the moment, as we are experiencing a large number of contributions! 

> I would like to remind you this is supposed to be a demo, and while we are very grateful for your work. We ask all Outreachy candidates to work on a minimum of 3 projects simultaneously so that they are not completely relying on their selection in OSCSA if we end up not selecting them!

Thank you again for all your wonderful work 🌷

**Comment by RealRichi3** [comment]
@sandygudie let's use GitHub discussions for communicating instead

**Comment by anslemkelechi** [comment]
> Hello Team, While waiting on feedback from @BatoolMM Please, Let's have a call by 5 PM WAT today( 9 AM PST) https://meet.google.com/zth-eoem-nnx

Would be joining the meeting as i would like to contribute.

**Comment by anslemkelechi** [comment]
> @sandygudie let's use GitHub discussions for communicating instead

I think i agree with this.

**Comment by mufidat3250** [comment]
I would Like to contribute to this project I have Knowledge of React and firebase i also want to ask if there is as existing design or we need to come up with design while implementing the UI

**Comment by sandygudie** [comment]
Hello Team, meeting starts in 5mins

**Comment by anslemkelechi** [comment]
> 

Hi sandy,
Have you uploaded the link to the doc as discussed in the call?

If you have how can I get it, please?

**Comment by anslemkelechi** [comment]
> > 
> 
> Hi sandy, Have you uploaded the link to the doc as discussed in the call?
> 
> If you have how can I get it, please?

Seen it already ☺
Thanks

**Comment by RealRichi3** [comment]
@sandygudie have you contacted @BatoolMM regarding the branches we would need?

**Comment by mildrette** [comment]
Hello everyone, Please I will love to contribute to this project too. please add me to it thank you.

**Comment by RealRichi3** [comment]
Sure, by tomorrow a list of tasks will be sent here, just pick anyone you feel you can handle

**Comment by RealRichi3** [comment]
@sandygudie i have made the issue for collaboration on the backend API here's the link #5. 
Please remember to make the necessary update

**Comment by Eshy10** [comment]
Hi everyone, I would like to contribute to this project. How do I join looking forward to hearing from you guys. I am skilled in HTML, CSS, JavaScript, React, Nextjs, Vuejs, Ruby on Rails, Typegraphql.

**Comment by yukiyuli** [comment]
Hello everyone, I'm an Outreachy applicant. I'm interested in this project. I have knowledge of  HTML, CSS, JavaScript and vue.

**Comment by sandygudie** [comment]
Thank You Team for yesterday's meeting, The information shared was insightful. Feel free to visit the [docs](https://docs.google.com/document/d/1S31oJKEVf-ywlTEDUf4dHDiUVmCbYWVYE1QbPScLFis/edit)
We were able to break down tasks in different areas(Design, Frontend, Backend) so that everyone can contribute.
Looking forward to the exciting work ahead!👏

**Comment by mildrette** [comment]
@sandygudie  please I will love to work on these tasks for the front-end  
- Landing page 
- Header
- Footer

**Comment by safa-ismail** [comment]
@sandygudie  as per discussion will the issues be created for each areas today ??

**Comment by RealRichi3** [comment]
Thanks @BatooIMM, if you will be available for the zoom sessions, we got some suggestions and questions concerning the branches for each proposal

**Comment by sandygudie** [comment]
https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/2#issuecomment-1278105762

Yes Please we hoping to discuss that tomorrow

**Comment by GuddyTech** [comment]
Hello @sandygudie can I join the team to collaboratively achieve some of these tasks? Thanks

**Comment by sandygudie** [comment]
Yes sure @GuddyTech

**Comment by ladyami** [comment]
@sandygudie is there a UI for this project?

**Comment by sandygudie** [comment]
@ladyami, UI is in development, some pages are pending [Issue](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/11)

**Comment by ladyami** [comment]
@sandygudie can I design the pending pages if so what pages are pending? and also in development what task is available?

**Comment by yukiyuli** [comment]
Is there anything I can contribute? I have knowledge of HTML, CSS, JavaScript, and Vue.

**Comment by ladyami** [comment]
@sandygudie  Okay I will work on it thank you

**Comment by ladyami** [comment]
@oEbuka  I don't need to make another design I thought you stop working on that is why I want to pick it up let use yours

**Comment by ladyami** [comment]
@oEbuka can you please send me the link to the Figma design because the one I see does not have a setting page admin dashboard and profile page

**Comment by GuddyTech** [comment]
@sandygudie can any task be assigned to me I know HTML, CSS and React. Can we also have a slack channel or discord to enable us interact more on the tasks and how to run them. A google meet would also be appreciated. Thanks in anticipation.

**Comment by Rubadel** [comment]
I also want to join with for this task, plz could you let me know about your working now? 
I have a well plan and a good experience for technology for this task ..

**Comment by BatoolMM** [comment]
Thank you to everyone for their amazing work 🌷, @sandygudie can you update the main issue by adding more details about the progress by referencing PRs? Also, make sure you reference PRs and issues by their number, not as markdown syntax as I fixed the ones in the "DEVELOPMENT PROCESS". Let me know if this is not clear!

**Comment by Teslimsama** [comment]
het @BatoolMM  i just want to confirm which branch are going to pull requests for

**Comment by sandygudie** [comment]
> Thank you to everyone for their amazing work 🌷, @sandygudie can you update the main issue by adding more details about the progress by referencing PRs? Also, make sure you reference PRs and issues by their number, not as markdown syntax as I fixed the ones in the "DEVELOPMENT PROCESS". Let me know if this is not clear!

@BatoolMM Please review the main issue update, is it in line with what you have in mind?
I will update the Backend PRs when @RealRichi3 updates the Backend issue

**Comment by BatoolMM** [comment]
I love the update you added @sandygudie.
@Teslimsama I belive `dev_team2` but it depends on what you will do, @sandygudie can let you know.
