### ISSUE TITLE
Creating a Sign Up Page for MOOC (dev_team2 branch)

### ISSUE THREAD

**Issue by Dhei-vid** [Open-Science-Community-Saudi-Arabia/MOOCs#29]
### Summary

Creating a Sign Up Page from this [design](https://www.figma.com/file/mkhBuJAS2arzy3wrbTZp2D/Simple-Landing-page-for-OSCSA%2C-with-Log-In-and-Sign-Up-Pages). This issue addresses [#10](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/10) and references  #24. And is to be handled in dev_team2 branch. 

### What tasks should be worked on

- [ ] Create a Sign Up page

### What needs to be done?

✅ Display the Sign Up page ReactJS

### Who want to work on this issue?

@Dhei-vid

**Comment by Dhei-vid** [comment]
@BatoolMM I'd like this to be assigned to me

**Comment by okerekechinweotito** [comment]
@Dhei-vid  This is already been addressed in #24

**Comment by BatoolMM** [comment]
@Dhei-vid Thank you for opening this issue. If it was already addressed, can you close this one, please?
