### ISSUE TITLE
General Fixs

### ISSUE THREAD

**Issue by sandygudie** [Open-Science-Community-Saudi-Arabia/MOOCs#326]
Issue description
- Fixes includes page styling for English and arabic view
- Fixed Github action for the merge crowdin
- Netlify deployment fixes

**Comment by sandygudie** [comment]
@BatoolMM 
I have changed the netlify settings for deployment preview, from frontend-ui to main
![image](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/assets/54219127/0c5bcf3a-8571-4e85-9d0a-f2927c3dece8)

**Comment by BatoolMM** [comment]
That's fantastic, waw, thank you 🙏
