### ISSUE TITLE
Video search feature 

### ISSUE THREAD

**Issue by Teslimsama** [Open-Science-Community-Saudi-Arabia/MOOCs#4]
<h1>I would like take on this issue using PHP MySQL</h1>

**Comment by BatoolMM** [comment]
@Teslimsama Thank you for openning an issue. Any issue that doesn't use our issue template will be removed. Can you re-edit the issue according to the template, please?

**Comment by Teslimsama** [comment]
@BatoolMM I don't know the template

**Comment by BatoolMM** [comment]
Any issue should have a clear description of what you are trying to do and a clear title, and a reference to other issues (if needed). I fixed the template, which you can access it when you click on the issues. 

![Screenshot 2022-10-12 at 13 54 55](https://user-images.githubusercontent.com/53487593/195348288-41fcdc40-4f32-41c2-a2ee-400ac367305d.png)

let me know if you have any other question!

**Comment by Teslimsama** [comment]
Thanks
