### ISSUE TITLE
[21/10/2022]: Add a detailed README .md file to the dev_team2 branch

### ISSUE THREAD

**Issue by JulianaSau** [Open-Science-Community-Saudi-Arabia/MOOCs#70]
#### Description

- *Update the README.md to include important information*

#### Which task are you working on?

- [ ] *Addresses one of the tasks stipulate in issue #10 *

### What needs to be done?

- [ ] *Update the README with relevant information to new contributors*
- [ ] *Update the readme to include important information about the repository*

### Who want to work on this issue?

I would like to be assigned to work on this issue

**Comment by okerekechinweotito** [comment]
@JulianaSau  Please what is the update on this issue ?

**Comment by JulianaSau** [comment]
Hi @okerekechinweotito , I'm submitting a PR in a few minutes

**Comment by okerekechinweotito** [comment]
@JulianaSau alright
