### ISSUE TITLE
[24/10/2022]: Create/Upload Course (restricted to admin).

### ISSUE THREAD

**Issue by oEbuka** [Open-Science-Community-Saudi-Arabia/MOOCs#86]
Sub Issue : https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/5#issue-1406773854
### Summary

Only Admins can create and upload courses.

### What needs to be done?

- [x] Create/Upload Course (restricted to Admin).

### Who want to work on this issue?
Assigned to me by @RealRichi3

**Comment by oEbuka** [comment]
@RealRichi3 I made changes, added, committed and then pushed to github. I am not seeing a PR on github for reasons unknown to me.
Also I made a new branch for this task. Are you familiar with this type of issue?

**Comment by RealRichi3** [comment]
When did you make the PR?

**Comment by RealRichi3** [comment]
@oEbuka if your referring to  PR for the models #25, it has been merged already

**Comment by oEbuka** [comment]
> @oEbuka if your referring to PR for the models #25, it has been merged already

Good day, I wasn't referring to this. Thanks.
When I try to push to upstream, I'm restricted.
When I push to origin it's says my branch is behind. So I pull, it shows the additions, but when I commit it shows there's 'nothing to commit', then when I push again it's still says the branch is behind.

**Comment by RealRichi3** [comment]
First, you can't push to upstream because you have no permission. Try synchronizing `dev_team2` branch on the forked repository in your GitHub account. Then pull again
